image: go_builder
matrix:
  - env: GO_VERSION=go1.9

before_install:
  - gvm install $GO_VERSION -B
  - gvm use $GO_VERSION --default
  - gvm linkthis $ABSTRUSE_BUILD_DIR
  - go get -u github.com/golang/dep/cmd/dep

install:
  - cd $GOPATH/src/$ABSTRUSE_BUILD_DIR && dep ensure -vendor-only
  - ls $GOPATH/src/github.com

script:
  - go test -v ./...